"""Base vs. Chat model: how predictable and how cacheable is each, per
prompt category?

    python -m expertrelay.bench.store_comparison
    python -m expertrelay.bench.store_comparison --report

Offline, from finished traces of both stores. For each store and each
category, on the TEST prompts (even-numbered, as in
bench/phase35_prediction.py): recall of the Fate-style guess at top-k
(generated tokens, layers 1-23; Z. Fang et al., arXiv:2502.12224), and of
the previous-token guess. Popularity and LRU cache hit rates per category
come from each store's latest Phase 3 analysis record.

The two runs differ in more than weights: the Chat store's prompts are
wrapped in the ChatML template (longer prefill, a system prompt), and its
answers are generated by an instruction-tuned model. Differences below are
differences between those two setups, not the effect of fine-tuning alone.

Writes benchmarks/results/store_comparison.json and docs/base-vs-chat.md.
"""

from __future__ import annotations

import argparse
import json

import numpy as np

from expertrelay import REPO_ROOT
from expertrelay.bench.phase3_analysis import load_traces
from expertrelay.bench.phase3_traces import DEFAULT_CONFIG, round_robin, trace_dir_for
from expertrelay.bench.phase35_prediction import RECALL_KS, flat, recency, split_halves, stack, to_seq
from expertrelay.benchmarking import append_benchmark_record, base_record, peak_process_rss_mb
from expertrelay.manager.profile import collect_machine_profile
from expertrelay.memory_budget import enforce_ram_budget
from expertrelay.paths import BENCHMARK_RESULTS_DIR
from expertrelay.predictor.offline import topk_hits
from expertrelay.runtime.generate import RuntimeConfig

STORES = {"base": "qwen1.5-moe-a2.7b-int8", "chat": "qwen1.5-moe-a2.7b-chat-int8"}
OUT = BENCHMARK_RESULTS_DIR / "store_comparison.json"
DOC = REPO_ROOT / "docs" / "base-vs-chat.md"
MAX_RAM_GB = 1.0
RAM_PER_TRACE_BYTE = 7  # as bench/phase35_prediction.py: same arrays
CACHE_CAPACITY = 192  # 1.66 GB, for the per-category LRU hit rate


def recall(seqs) -> dict:
    later = slice(1, None)
    truth = flat(stack(seqs, "experts"), later)
    fate = flat(stack(seqs, "fate"), later)
    prev = flat(recency(seqs, 1.0), later)  # decay 1, window 8: "used in the last 8 tokens"
    top = truth.shape[1]
    return {
        "tokens": int(sum(len(s.experts) - s.prompt_len for s in seqs)),
        "fate": {str(k): float(topk_hits(fate, truth, k).mean() / top) for k in RECALL_KS},
        "recent_8_tokens": {str(k): float(topk_hits(prev, truth, k).mean() / top) for k in RECALL_KS},
    }


def phase3_numbers(store: str) -> dict:
    a = json.loads((BENCHMARK_RESULTS_DIR / f"phase3_analysis_{store}.json").read_text())[-1]["analysis"]
    caps = a["cache"]["by_category"][next(iter(a["cache"]["by_category"]))]["capacities"]
    i = caps.index(CACHE_CAPACITY)
    return {
        "popularity_top10_share": {
            c: v["top10pct_share_mean"] for c, v in a["popularity"]["by_category"].items()
        },
        "lru_hit_rate_at_192": {
            c: v["policies"]["lru"]["decode_hit_rate"][i] for c, v in a["cache"]["by_category"].items()
        },
        "belady_hit_rate_at_192": {
            c: v["policies"]["belady"]["decode_hit_rate"][i] for c, v in a["cache"]["by_category"].items()
        },
    }


def analyze_store(store: str, prompt_ids: list[str]) -> dict:
    trace_dir = trace_dir_for(REPO_ROOT / "models" / store)
    done = [pid for pid in prompt_ids if (trace_dir / f"{pid}.done.json").exists()]
    enforce_ram_budget(
        sum((trace_dir / f"{pid}.ert").stat().st_size for pid in done) * RAM_PER_TRACE_BYTE,
        MAX_RAM_GB,
        f"store comparison ({store})",
    )
    seqs = [to_seq(t) for t in load_traces(trace_dir, done)]
    _, test = split_halves(seqs)
    cats = sorted({s.category for s in test})
    return {
        "prompts": len(seqs),
        "test_prompts": len(test),
        "prompt_tokens_mean": float(np.mean([s.prompt_len for s in seqs])),
        "all": recall(test),
        "by_category": {c: recall([s for s in test if s.category == c]) for c in cats},
        "phase3": phase3_numbers(store),
    }


def _pct(x: float) -> str:
    return f"{x:.1%}"


def format_markdown(record: dict) -> str:
    a = record["analysis"]
    b, c = a["base"], a["chat"]
    cats = sorted(b["by_category"])
    lines = [
        "# Base vs. Chat: expert usage compared",
        "",
        f"Generated by `python -m expertrelay.bench.store_comparison` at {record['timestamp']} "
        f"(commit {record['git_commit'][:7]}{', dirty tree' if record['git_dirty'] else ''}) from "
        "`benchmarks/results/store_comparison.json`. Do not edit by hand.",
        "",
        f"96 prompts per store, 128 generated tokens each; recall is on the {b['test_prompts']} test prompts "
        "(even-numbered in each category), generated tokens, layers 1-23. The Chat store's prompts are "
        "wrapped in its ChatML template, so its prefill is longer "
        f"({c['prompt_tokens_mean']:.0f} vs {b['prompt_tokens_mean']:.0f} tokens on average) and includes a "
        "system prompt: differences are between the two setups, not fine-tuning alone. Full per-store "
        "analyses: `docs/phase3-analysis.md` (base) and "
        "`docs/phase3-analysis-qwen1.5-moe-a2.7b-chat-int8.md` (Chat).",
        "",
        "## Fate-style guess, one layer ahead: share of the true 4 experts caught",
        "",
        "| category | base top-4 | Chat top-4 | base top-8 | Chat top-8 | base top-12 | Chat top-12 |",
        "|---|---|---|---|---|---|---|",
    ]
    for cat in [*cats, "all"]:
        rb = b["all"] if cat == "all" else b["by_category"][cat]
        rc = c["all"] if cat == "all" else c["by_category"][cat]
        lines.append(
            f"| {'**all**' if cat == 'all' else cat} | "
            + " | ".join(f"{_pct(rb['fate'][k])} | {_pct(rc['fate'][k])}" for k in ("4", "8", "12"))
            + " |"
        )
    lines += [
        "",
        "## Reuse: share of the true 4 caught by the experts used in the last 8 tokens (top-4 / top-8)",
        "",
        "| category | base | Chat |",
        "|---|---|---|",
    ]
    for cat in [*cats, "all"]:
        rb = b["all"] if cat == "all" else b["by_category"][cat]
        rc = c["all"] if cat == "all" else c["by_category"][cat]
        lines.append(
            f"| {cat} | {_pct(rb['recent_8_tokens']['4'])} / {_pct(rb['recent_8_tokens']['8'])} | "
            f"{_pct(rc['recent_8_tokens']['4'])} / {_pct(rc['recent_8_tokens']['8'])} |"
        )
    pb, pc = b["phase3"], c["phase3"]
    lines += [
        "",
        f"## Popularity and caching (all prompts of the category; LRU and Belady at {CACHE_CAPACITY} experts, 1.66 GB)",
        "",
        "Top-10% share: the share of selections that go to each layer's 6 most-used experts (10% if routing "
        "were uniform). Cache hit rates: decode, the category's prompts replayed back to back.",
        "",
        "| category | top-10% share base / Chat | LRU base / Chat | Belady base / Chat |",
        "|---|---|---|---|",
    ]
    for cat in cats:
        lines.append(
            f"| {cat} | {_pct(pb['popularity_top10_share'][cat])} / {_pct(pc['popularity_top10_share'][cat])} | "
            f"{_pct(pb['lru_hit_rate_at_192'][cat])} / {_pct(pc['lru_hit_rate_at_192'][cat])} | "
            f"{_pct(pb['belady_hit_rate_at_192'][cat])} / {_pct(pc['belady_hit_rate_at_192'][cat])} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()
    if args.report:
        DOC.write_text(format_markdown(json.loads(OUT.read_text())[-1]), encoding="utf-8")
        print(f"wrote {DOC}")
        return
    rt = RuntimeConfig.load(DEFAULT_CONFIG)
    prompt_ids = [
        p["id"] for p in round_robin(json.loads(rt.prompts_file.read_text(encoding="utf-8"))["prompts"])
    ]
    record = base_record(
        label="base vs chat store: expert usage per category",
        seed=0,
        model={"stores": STORES},
        config={"recall_ks": RECALL_KS, "cache_capacity": CACHE_CAPACITY, "split": "odd tune / even test"},
        machine=collect_machine_profile(measure_disk=False),
    )
    record["analysis"] = {name: analyze_store(store, prompt_ids) for name, store in STORES.items()}
    record["peak_rss_mb"] = peak_process_rss_mb()
    append_benchmark_record(OUT, record)
    DOC.write_text(format_markdown(record), encoding="utf-8")
    print(f"saved {OUT} and {DOC}")


if __name__ == "__main__":
    main()
